/** Static routes derived from src/content — kept in sync with the site map. */
export const STATIC_ROUTES = [
  '/',
  '/articles',
  '/articles/2',
  '/articles/embed-preview',
  '/articles/series-demo',
  '/articles/series-demo/1',
  '/articles/series-demo/2',
  '/articles/pkm-method',
  '/articles/heptabase-method',
  '/projects',
  '/projects/maker-plan',
  '/projects/robert',
  '/projects/network',
  '/projects/trace',
  '/projects/aletheia',
  '/projects/ethanchang-io',
  '/projects/craft-space',
  '/projects/chunk',
  '/projects/deeptalk',
  '/now',
  '/about',
  '/search',
  '/tags',
  '/tags/PKM',
  '/lab',
  '/zh',
  '/zh/now',
  '/zh/articles',
  '/zh/articles/pkm-method',
  '/zh/projects',
  '/zh/search',
  '/zh/tags',
] as const;

export const KEY_PAGES_FOR_LINK_CHECK = [
  '/',
  '/articles',
  '/projects',
  '/now',
  '/search',
  '/tags',
  '/lab',
  '/zh',
] as const;
